name: Release Please

on:
  push:
    branches:
      - master   # main에 머지되면 실행

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node        # Next.js도 Node.js 기반
          package-name: my-nextjs-app
