import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Web languages",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  );
}
