name: PR Labeler

on:
  pull_request:
    types: [opened, edited]
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}