name: pr labeler
on:
  pull_request:
    types: [opened]
    branches:
      - master
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}