name: Daily Release Note

on:
  schedule:
    # 매일 오전 0시(KST 기준 약간 조정 필요)
    - cron: '0 0 * * *'

jobs:
  create_daily_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Release Version
        run: |
          DATE=$(date +'%Y.%m.%d')
          echo "VERSION=daily-$DATE" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create $VERSION \
            --title "Daily Release $VERSION" \
            --notes "### Changes on $VERSION 
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}